---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  changelog:
    name: Enforce CHANGELOG
    uses: ./.github/workflows/changelog.yml

  configs-verifier:
    name: Verify configs
    uses: ./.github/workflows/configs-verifier.yml

  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml
    needs: [changelog, configs-verifier]

  rust_build:
    name: Build Rust project
    uses: ./.github/workflows/rust-build.yml
    needs: [changelog, configs-verifier]

  linters_cargo:
    name: Run Cargo linters
    uses: ./.github/workflows/linters-cargo.yml
    needs: rust_build

  tests:
    name: Run tests and coverage
    uses: ./.github/workflows/tests-coverage.yml
    needs: rust_build

  # benchmark:
  #   name: Run benchmarks
  #   uses: ./.github/workflows/benchmarks.yml
  #   needs: [rust_build, tests]
  #   permissions:
  #     # deployments permission to deploy GitHub pages website
  #     deployments: write
  #     # contents permission to update benchmark contents in gh-pages branch
  #     contents: write
  #     # post on the pull-request page
  #     pull-requests: write
